---
name: Build PDF

on:
  push:
    branches:
      - main
    paths:
      - ospo-book/**
  pull_request:
    branches:
      - main
    paths:
      - ospo-book/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Gather input
        id: gather
        run: echo "files=$(ls ospo-book/chapters/*.md | xargs)" >> $GITHUB_OUTPUT
      - name: Install TeXlive
        run: |
          sudo apt-get update
          sudo apt-get install texlive texlive-publishers texlive-science latexmk cm-super texlive-base texlive-latex-recommended texlive-science texlive-latex-extra texlive-extra-utils
      - name: Generate book
        run: |
          pandoc -N -s --template=ospo-book/docs/template.latex --output ospo-book/docs/output.pdf ${{ steps.gather.outputs.files }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: book-pdf
          path: ospo-book/docs/output.pdf
